<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <script>
        // const p1 = new Promise((resolve,reject)=>{
        //     console.log('exectue函数执行');
        //     setTimeout(()=>{
        //         const num = new Date();
        //         if(num%2===0){
        //             resolve('这是一个偶数'+num);
        //         }else{
        //             reject('这是一个基数'+num);
        //         }
        //     },1000)
        // });

        // const p2 = new Promise((resolve,reject)=>{
        //     // reject(2);
        //     throw new Error('zheli paochu error');
        // })

        // const p3 = new Promise((resolve,reject)=>{
        //     Promise.reject(2);
        // })

        // p1.then((result)=>{
        //     console.log('p1 jieshou',result);
        // },(reason)=>{
        //     console.log('p1 jieshou',reason);
        //     throw new Error (reason);
        // }).catch((error)=>{
        //     console.log(error);
        // });

        // p2.then((result)=>{
        //     console.log(result);
        // }).catch((error)=>{
        //     console.log(error);
        // })
        
        // try{
        //     p2.then(
        //         (result)=>{
        //             console.log('p2 jieshou',result);
        //         },
        //         (reason)=>{
        //             console.log('p2 jieshou',reason);
        //         }
        //     )
        // }
        // catch{(error)=>{
        //     console.log('p2 jieshou',error);
        // }}

        // const p2 = Promise.resolve(2);
        // const p3 = Promise.reject(3);

        // p1.then((result)=>{
        //     console.log(result);
        // })

        // p2.then((result)=>{
        //     console.log(result);
        // })

        // p3.then((result)=>{
        //     console.log(result);
        // }).catch((err)=>{
        //     console.log(err);
        // })

        // Promise.all([p1,p2,p3]).then((result)=>{
        //     console.log(result);
        // }).catch((err)=>{
        //     console.log(err);
        // })

        // Promise.race([p1,p2,p3]).then((result)=>{
        //     console.log(result);
        // }).catch((e)=>{
        //     console.log(e);
        // })
        
        // const p4 = new Promise((resolve,reject)=>{
        //     // resolve(1);
        //     // reject(2);
        //     throw new Error('new Error');
        // })

        // p4.then(
        //     (result)=>{
        //         console.log('suc',result);
        //     },
        //     (reason) =>{
        //         console.log('fai',reason);
        //     }
        // )

        // p4.then(
        //     (result)=>{
        //         console.log('suc1',result);
        //     },
        //     (reason) =>{
        //         console.log('fai1',reason);
        //     }
        // )

        const p1 = new Promise((resolve,reject)=>{
            const data1 = [1,2,3,4,5];
            setTimeout(()=>{
                resolve(data1);
            },1000)
        })
        // const p2 = new Promise((resolve,reject)=>{
        //     const data2 = [2,2,2]
        //     return data2;
        // })
        // const p3 = new Promise((resolve,reject)=>{
        //     const data3 = [3,3,3]
        //     setTimeout(()=>{
        //         resolve(data3);
        //     },1000)
        // })
        const p2 = new Promise((resolve,reject)=>{
            const data2 = [2,2,2,2]
            setTimeout(()=>{
                resolve(data2)
            },1000)
        })

        p1.then((result)=>{
            console.log(result);
            return new Promise((resolve,reject)=>{
                setTimeout(()=>{
                    resolve(result);
                },1000) 
            })
        }).then((result)=>{
            console.log('这是我从上个回调中拿的值',result);
            return p2
        }).then((result)=>{
            console.log('这又是从上一个回调中取得值',result);
            if(result){
                // Promise.reject(3);
                return new Promise((resolve,reject)=>{
                    reject(3);
                })
            }
        }).catch((err)=>{
            console.log('这里是我捕获的异常',err);
        })
        // p1.then((result)=>{
        //     console.log(result);
        //     return new Promise((resolve,reject)=>{
        //         const data2 = [2,2,2]
        //         resolve(data2);
        //     })
        // }).then((result)=>{
        //     console.log(result);
        // })




    </script>
</body>
</html>